version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MODEL_PATH=my_model.keras
      - HOST=0.0.0.0
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - CORS_ORIGINS=https://salmon-pebble-03691881e.2.azurestaticapps.net
    restart: unless-stopped
